url: https://JJediny.github.io
baseurl: /me/

# Site settings
title: John Jediny
email: John.Jediny@gmail.com
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 003f80
  secondary: 0060c2
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

#- name:
#  pic: 2
#  position:
#  social:
#    - title:
#      url: #
#    - title:
#      url: #
#    - title:
#      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jjediny
  - title: facebook
    url:
  - title: google
    url: http://google
  - title: github
    url: http://github.com/JJediny

# Postal address (add as many lines as necessary)
address:
  - line: 973-931-0580
  - line: Washington, DC

# Build settings
markdown: kramdown
permalink: pretty
